# 此页内容已被童年是个风筝（sctop）更新过
# 原内容请自行fork原项目：https://github.com/kaeyleo/jekyll-theme-H2O

# --------------------------------------------------------------------------
# |文章底纹（当文章没有底纹图片时），中英文对照：                          |
# |circuitBoard           电路                                             |
# |overlappingCircles     圆环                                             |
# |food                   吃货日常：肯打鸡                                 |
# |glamorous              土豪必备：钻石                                   |
# |ticTacToe              圈圈叉叉                                         |
# |seaOfClouds            中国风：云海                                     |
# |                   默认为ciruitBoard（电路）                            |
# |                       配置：85行开始                                   |
# --------------------------------------------------------------------------

# -----------------------------------------
# |配置社交网站url（中英文对照）:         |
# |weibo     微博                         |
# |zhihu     知乎                         |
# |twitter   推特                         |
# |instagram                              |
# |juejin    掘金                         |
# |github                                 |
# |douban    豆瓣                         |
# |facebook  脸书                         |
# |dribble                                |
# |uicn      UI中国                       |
# |jianshu   简书                         |
# |medium                                 |
# |linkedin  领英                         |
# |         配置：90行开始                |
# -----------------------------------------

# Site settings 配置站点
title: '童年是个风筝的博客'
description: '小名宝仔，Scratch语言爱好者，河源市第一小学五年级小学狗一名。现在致力于管理网站和写博客文章。'  # 搜索引擎蜘蛛捕捉的内容
keyword: '童年是个风筝, 童年是个风筝的博客, 张颀润'
url: 'https://www.zhangqirun.cn/' # your host / 你的域名（注意这里有https就写上https，否则的话到时候会有引用不安全资源的问题）

# if you don't need baseurl, you should leave this value blank.
baseurl: ''

# index 首页
home-title: '童年是个风筝的博客'
home-description: 'zhangqirun.cn，更易识别，权重更高'

# Navigation links  导航链接
# /links.html 和 /feed.xml 请勿添加到这里！
nav:
  home: '/'
  tags: '/tags.html'
  VistalStudio: '/VisualStudio2017.html'
  
# RSS订阅
RSS: true

# Author 配置博主信息
# author真名 nickname小名 bio简介 avatar头像 old年龄 from来自于哪里（最好写清楚省份城市）
author: '张颀润'
nickname: '宝仔'
bio: '广东省河源市第一小学五年级的小学狗一名，热爱写博客&搞东西。爱PR，爱Scratch，爱b站和many things。现在致力于管理网站和写博客文章，对大千世界有着自己的见解。同学们中间的电脑高手（滑稽）。'
avatar: '/assets/img/profile.jpg'
old: '11'
from: '广东河源'

# Search  搜索
search: true

# Night mode  夜间模式
nightMode: true

# Comments 评论功能
#   default_hidden：是否默认隐藏评论。若是则需要点击一按钮后才显示。 by Ray-Eldath
comments:
  default_hidden: false
  disqus: false
  disqus_url: ''

  livere: true
  livere_uid: MTAyMC8zMzc5Ni8xMDM0OQ==
# --------
# b2t 回到顶部 by Ray-Eldath
b2t: true

# MathJax 公式支持 by Ray-Eldath
mathjax: true

# Share  分享
# 第一个是是否开启，第二个是分享的渠道
social-share: true
social-share-items: ['weibo', 'qq', 'tencent', 'douban', 'qzone', 'linkedin', 'diandian', 'facebook', 'twitter', 'google']

# theme color 主题皮肤
theme-color: 'default'  # pink or default  粉色或者默认（蓝色）

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
# 文章底纹（当文章没有配图片时的默认背景）
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站url
# 详细可参照16~32行
sns:
  github: '//github.com/sctop'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings  生成设置
# paginate 每一页显示的文章个数  paginate_path 设置文章每一页显示的个数  exclude 不生成的文件/文件夹，需要绝对路径，文件夹直接写文件夹名字，文件名需带后缀
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Plugins
gems: [jekyll-paginate]

# 以下内容为童年是个风筝添加
# 时区设定
timezone: Asia/Shanghai

# 强制限制
encoding: UTF-8

# 网站状态
# 一次只能true一个，否则会有异常
# close网站暂时关闭 never网站永远关闭 newsite_url是配置never后的新网址
close: false
never: false
newsite_url: ''

# 联系方式
mp: '' # 联系手机号
phone: '' # 联系座机
qq: '2094880085' # 联系QQ
mail: 'feedback@zhangqirun.cn' # 联系邮箱

# 统计&管理网站
# 网站备案后请立即填写ICP备案并且立即查看ICP备案是否在底部并且能否链接到工信部官网
ICP: '' # （如果有）网站备案，强烈建议填写！！！！

baidutj: 'https://hm.baidu.com/hm.js?96736cf6e5a2a329a74ae83047b92073' # 百度统计代码js网址（hm.src片段）
baidusszypt: 'mKtf56wzTi' # 百度搜索资源平台验证，验证用
baiduunion: 'c8504856a19f1bd4b39d67876b99707c' # 百度联盟（广告投放）验证
baidusszyptautolink: true # 百度自动提交链接

bingtj: '60C8EBAF57EF518899B5C5D16D8D2ADB' # 必应网站管理（content片段）

360zzpt: 'e48fdf9149fc8979dcc34b91fa988767' # 为360站长平台（content片段），验证用
360autolinks: true # 360自动提交链接

# CloudFlare CDN
cloudflare:
  loading_js: ture # 手动加载js

# 赞赏
# 这里使用的是<a>标签跳转，所以要填写link。赞助项目地址：https://github.com/sctop/subsidize/ 
# open是启用/不启用（默认true启用） link是跳转地址 info是指当鼠标停留在图标上时显示的
zanshang:
  open: true
  link: 'https://zizhu.zhangqirun.cn/'
  info: '真诚赞赏 手有余香'

# 谷歌广告
googleads:
  googleadson: true # 启用广告？
  auto_ad: false # 自动广告
  tqads: false # 弹窗内广告
  index: true # （电脑端可用）首页右侧
  indexposts: true # 首页文章排列下方
  headposts: true # 文章头部显示
  downposts: true # 文章底部显示
  phonedbads: false # （移动端可用）底部固定式覆盖弹窗
  footerads: true # 底部广告
# --------------------------
# 友情链接
# 这里是优质友情链接
haolinks: true
goodlinks:
  博客模板支持: 'http://jekyllthemes.org'
  Liquid（jekyll）模板的食用方法(⌒▽⌒): 'https://liquid.bootcss.com/'
  Jekyll中文翻译版教程: 'http://jekyllcn.com/'
  Jekyll原版教程: 'https://jekyllrb.com/'
  Townwang的博客: 'https://townwang.com/'
# ---分界线---
# 这里是普通友情链接（相对于优质的友情链接较低级一些的）
putonglinks: true
ptlinks:
  空白代刷站: 'http://likebuying.top/'
  空白君的博客: 'http://kbboke.xyz/'
  fttidc主机: 'http://fttidc.com/'
# ---分界线---
# 这里是提供服务的赞助（服务提供）商。
zzlinks: true
zanzhulinks:
  腾讯云: 'https://cloud.tencent.com/'
  CloudFlare云服务: 'https://www.cloudflare.com/'
# ---分界线---
# 这里是博主开办的网页
bzlinks: true
bozhulinks:
  博主开发的软件的下载站: 'https://microsoft.zhangqirun.cn/'
  资助: 'https://zizhu.zhangqirun.cn/'
  下载内容缓存: 'https://down.zhangqirun.cn/'
  旧博客: 'https://blog.zhangqirun.cn/'
  空白君旧博客缓存: 'https://kb.zhangqirun.cn/'
# ---分界线---
# 这里是友情链接网站正在维修的
errorlinks: false
siteerrorlinks:
  No any things: 'NO-ANY-THINGS'
# ---分界线---
# 底部
360webscanopen: 'true' # 360网站安全显示
360webscanshowbig: 'true' # 360网站安全显示图标是否是大图标
360scanurl: 'zhangqirun.cn' # 360网站安全检测的域名（不要带https://或http://，也不要带主机名）
startyear: '2017' # 开始搭建博客的年份
# cnzz
cnzzdata: 'true' # cnzz横排数据是否显示
cnzzzxrs: 'true' # cnzz在线人数是否显示
cnzztj: 'true' # cnzz统计是否显示（启用）
cnzztjjs: 'https://s13.cnzz.com/z_stat.php?id=1271703809&web_id=1271703809' # cnzz统计js的src片段
dbxsxx: 'true' # 底部是否显示简介
codeurl: 'https://github.com/sctop/sctop.github.io/'
